### ISSUE TITLE
Combine multiple xml files using *.xml doesn't work

### ISSUE THREAD

**Issue by jonthierry** [kirankotari/xmlmerge#2]
Hello, when I try to merge multiple xml files using xmlmerge tests/*.xml > combine.xml command it produces a 0kb file with an error saying OSError: [Errno 22] Invalid argument: 'tests/*.xml'. Any help will be useful. I'm using windows.

**Comment by ravikolte** [comment]
@kirankotari - I am also getting the same error. 
PS C:\Users\acer\PycharmProjects\python> xmlmerge tests/*.xml > combine.xml
Traceback (most recent call last):
  File "C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python310\Scripts\xmlmerge.exe\__main__.py", line 7, in <module>
  File "C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\xmlmerge\xmlmerge.py", line 9, in run
    data = ElementTree.parse(filename).getroot()
  File "C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
OSError: [Errno 22] Invalid argument: 'tests/*.xml'
PS C:\Users\acer\PycharmProjects\python> 
i have the tests folder under python directory which has all the xmls

**Comment by kirankotari** [comment]
Can you mask the xml data and can you give us a sample to check.

**Comment by kirankotari** [comment]
I have published a new version, to show nice error message if you see wrong inputs. Please take the new one and lets us know if you are facing same issues

**Comment by ravikolte** [comment]
Hi Kiran,

I tried with the new version I am getting the same error message.
Please find the attached files.

These are sample files with which I am trying to create a merged xml file.

I am getting the same error I have mentioned on the github and in the new
file (merged file I am getting below)

Usage xmlmerge  <xml-files> > <new-file>
Usage xmlmerge  -csv <csv-file> <xml-files>
                -h | --help
xml files planning to merge are:
['tests/*.xml']

**Comment by kirankotari** [comment]
@ravikolte Can you add a screenshot for the same here, and I asked you run `dir your-xml-file-pattern`

**Comment by kirankotari** [comment]
@ravikolte @jonthierry @oboehmer No response for last 12 days closing the ticket.
