### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by woody544** [kirankotari/xmlmerge#9]
In git bash, on Windows 10, I am able to run the test files. However on my own files, I am getting a unicode error.
The file encoding is utf-8. I resaved the files as utf8-BOM, but this did not help and I am getting the same error. 

Can I stipulate the encoding, or make an exception? 

Thanks

`$ xmlmerge D:/ExHD-github/AnnotationData/SingleArticleExamples/HI-xml/*.xml > combine-HI.xml
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jd\AppData\Roaming\Python\Python39\Scripts\xmlmerge.exe\__main__.py", line 7, in <module>
  File "C:\Users\jd\AppData\Roaming\Python\Python39\site-packages\xmlmerge\xmlmerge.py", line 85, in run
    print(merge(files))
  File "C:\Users\jd\AppData\Roaming\Python\Python39\site-packages\xmlmerge\xmlmerge.py", line 15, in merge
    return ElementTree.dump(xml_data)
  File "c:\program files\python39\lib\xml\etree\ElementTree.py", line 1159, in dump
    elem.write(sys.stdout, encoding="unicode")
  File "c:\program files\python39\lib\xml\etree\ElementTree.py", line 748, in write
    serialize(write, self._root, qnames, namespaces,
  File "c:\program files\python39\lib\xml\etree\ElementTree.py", line 913, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "c:\program files\python39\lib\xml\etree\ElementTree.py", line 913, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "c:\program files\python39\lib\xml\etree\ElementTree.py", line 913, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "c:\program files\python39\lib\xml\etree\ElementTree.py", line 911, in _serialize_xml
    write(_escape_cdata(text))
  File "c:\program files\python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 183-184: character maps to <undefined>
`

**Comment by odisseus** [comment]
Could it be that the encoding declared in your XML headers doesn't match the actal encoding of the files?
